name: Build and Release RenameImage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
        
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: RenameImage_win_x64.exe
            asset_name: RenameImage_windows_x64.exe
          - os: ubuntu-latest
            output_name: RenameImage_linux_x64
            asset_name: RenameImage_linux_x64
          - os: macos-latest
            output_name: RenameImage_macos_x64
            asset_name: RenameImage_macos_x64
            
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --name ${{ matrix.output_name }} RenameImage.py
    
    - name: Build with PyInstaller (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --name ${{ matrix.output_name }} RenameImage.py
    
    - name: Build with PyInstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --name ${{ matrix.output_name }} RenameImage.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.output_name }}
        if-no-files-found: error

  release:
    needs: build
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Create Release
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          
      - name: Get Release Info
        id: get_release_info
        uses: bruceadams/get-release@v1.3.2
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'release' && steps.get_release_info.outputs.upload_url || steps.create_release.outputs.upload_url }}
          asset_path: ./RenameImage_windows_x64.exe/RenameImage_win_x64.exe
          asset_name: RenameImage_windows_x64.exe
          asset_content_type: application/octet-stream
          
      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'release' && steps.get_release_info.outputs.upload_url || steps.create_release.outputs.upload_url }}
          asset_path: ./RenameImage_linux_x64/RenameImage_linux_x64
          asset_name: RenameImage_linux_x64
          asset_content_type: application/octet-stream
          
      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event_name == 'release' && steps.get_release_info.outputs.upload_url || steps.create_release.outputs.upload_url }}
          asset_path: ./RenameImage_macos_x64/RenameImage_macos_x64
          asset_name: RenameImage_macos_x64
          asset_content_type: application/octet-stream
