name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: BatchImageRenamer.exe
            asset_name: BatchImageRenamer_windows.exe
          - os: ubuntu-latest
            output_name: BatchImageRenamer
            asset_name: BatchImageRenamer_linux
          - os: macos-latest
            output_name: BatchImageRenamer
            asset_name: BatchImageRenamer_macos

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "${{ matrix.output_name }}" rename_images_gui.py
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.output_name }}

    - name: Zip Source Code
      if: matrix.os == 'windows-latest'
      run: |
        Compress-Archive -Path *.py,locales,LICENSE,README.md,requirements.txt -DestinationPath BatchImageRenamer_Source.zip

    - name: Upload Source Code Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: source-code
        path: BatchImageRenamer_Source.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BatchImageRenamer_windows.exe/BatchImageRenamer.exe
          BatchImageRenamer_linux/BatchImageRenamer
          BatchImageRenamer_macos/BatchImageRenamer
          source-code/BatchImageRenamer_Source.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
