name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test imports
      run: |
        # 测试模块导入
        python -c "import os; import json; import locale; import tkinter; import threading; from language_manager import LanguageManager"
    - name: Test language manager
      run: |
        # 测试语言管理器基本功能
        python -c "from language_manager import LanguageManager; lm = LanguageManager(); print(f'Current language: {lm.get_current_language()}'); print(f'Supported languages: {lm.get_supported_languages()}')"